default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: mvpmoovlink_development
  username: <%= ENV['DB_USERNAME'] || "moovlink" %>
  password: <%= ENV['DB_PASSWORD'] || "moovlink123" %>
  host: <%= ENV['DB_HOST'] || "localhost" %>

test:
  <<: *default
  database: mvpmoovlink_test
  username: <%= ENV['DB_USERNAME'] || "moovlink" %>
  password: <%= ENV['DB_PASSWORD'] || "moovlink123" %>
  host: <%= ENV['DB_HOST'] || "localhost" %>

production:
  <<: *default
  database: <%= ENV['DB_NAME'] || "mvpmoovlink_production" %>
  username: <%= ENV['DB_USERNAME'] || "moovlink" %>
  password: <%= ENV['DB_PASSWORD'] || "moovlink123" %>
  host: <%= ENV['DB_HOST'] || "db" %>
